### ISSUE TITLE
请教个 preparedStatement 的问题，这里的写法是不是每次执行都会做一次 prepared？

### ISSUE THREAD

**Issue by 7yyo** [click33/sqlfly#1]
https://github.com/click33/sqlfly/blob/78268f915be3a2821c38b46eb88a27e462ae8ee1/sqlfly-dev/src/main/java/com/fly/jdbc/util/FlyDbUtil.java#L83

**Comment by click33** [comment]
应该是的

**Comment by click33** [comment]
应该是的
